AZURE_REPOS = [
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/googlechrome",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/7zip",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/adobereader",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/agentransack",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/azcopy10",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/azure-cli",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/azure-pipelines-agent",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/bginfo",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/checksum",
    # good above
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/curl",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/delprof2",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/dotNet",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/dotnetcore-sdk",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/dotnetfx",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/git",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/hp-universal-print-driver-pcl-master",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/microsoft-defender-platform",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/microsoft-monitoring-agent",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/microsoftazurestorageexplorer",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/nodejs",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/notepadplusplus",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/office2016",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/office2021",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/opconAgent",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/opconsqlagent",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/openssl",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/packer",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/pandoc",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/podman",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/podman-desktop",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/proget_maintenance",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/putty",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/pycharm-community",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/python3",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/qgis",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/sap-gui",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/scripts",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/setdefaultbrowser",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/solarwinds-agent",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/sql2012.nativeclient",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/sqlserver-odbcdriver",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/ssms19",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/sysinternals",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/terraform",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/uipathremoteruntime",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/vcredist2005",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/vcredist2008",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/vcredist2013",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/velero",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/visualstudio2019professional",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/visualstudio2022professional",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/vscode",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/webdeploy",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/winmerge",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/winscp",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/yarn",
    # "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/yml.pipeline",
]

not_in_public_repo = [
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/cisassessor",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/citrixPowerShell",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/citrixstorefront",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/citrixvda",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/citrixwemagent",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/citrixworkspace",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/dotnetfx35",
    "https://LDC-Technology-and-Operations@dev.azure.com/LDC-Technology-and-Operations/WPM-Chocolatey/_git/Ghostscript",

]